CREATE TABLE IF NOT EXISTS proyecto(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    descripcion text NOT NULL,
    monto integer NOT NULL,
    fecha date NOT NULL,
    estado  BOOLEAN 
    ); 
INSERT INTO proyecto(nombre,descripcion,monto,fecha,estado)
    VALUES('cualquier','descripcion muy especifica',100000,'2019-10-16',true);